CREATE DATABASE vet_clinic;
USE vet_clinic;

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN NOT NULL,
    weight_kg DECIMAL,
    species VARCHAR(255)
);

CREATE TABLE owners(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(255) NOT NULL,
    age INT,
    PRIMARY KEY(id)
)
CREATE TABLE species(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
)

ALTER TABLE animals 
    ADD CONSTRAINT animals_pk PRIMARY KEY (id);

ALTER TABLE animals
    DROP COLUMN species

ALTER TABLE animals
    ADD COLUMN species_id INT;
ALTER TABLE animals
    Add CONSTRAINT fk_species
    FOREIGN KEY (species_id)
    REFERENCES species (id);
ALTER TABLE animals
    ADD COLUMN owners_id INT;
ALTER TABLE animals
    ADD CONSTRAINT fk_owners
    FOREIGN KEY (owners_id)
    REFERENCES owners (id);